# Generated by Django 5.1.3 on 2025-02-03 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('semestre', models.CharField(max_length=1, null=True)),
                ('faltas', models.ManyToManyField(blank=True, to='aluno.faltas')),
            ],
        ),
    ]
