# Generated by Django 5.1.2 on 2024-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="password",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
