# Generated by Django 5.1.2 on 2024-11-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0002_aluno_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faltas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="aluno",
            name="faltas",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aluno.faltas",
            ),
        ),
    ]
