# Generated by Django 5.1.2 on 2024-11-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0003_faltas_alter_aluno_faltas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faltas",
            name="data",
            field=models.DateField(default=1, null=True),
        ),
    ]
