# Generated by Django 5.1.2 on 2024-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0004_alter_faltas_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="faltas",
        ),
        migrations.AlterField(
            model_name="faltas",
            name="data",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="faltas",
            field=models.ManyToManyField(blank=True, to="aluno.faltas"),
        ),
    ]
