# Generated by Django 5.1.3 on 2025-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_faltas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='semesters',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
